### PR TITLE
fix: Hide profile tabs.

### LINKED ISSUE #113: Hide features in profile that are "work in progress"
"Unfinished apps" may be rejected from the AppStore. 👉 Consider hiding the tabs from the profile for now.

image

### PR DESCRIPTION
**Pull request by wizlif**
Closes #113

### CODE REVIEW

File: lib/presentation/profile/profile_screen.dart [hunk 1]
```diff
@@ -292,7 +292,9 @@ class _UserProfilePageState extends State<UserProfilePage> {
                         ],
                       ),
                     ),
-                    UserProfileTab(user: state.userProfile?.user),
+                    Offstage(
```
Comment (rubenhorn) [inline lib/presentation/profile/profile_screen.dart:295]: Should we have the "Sign up" button on the anonymous profile instead?

**Review by rubenhorn — APPROVED** [review]
