### PR TITLE
fix(profile): change on logout

### LINKED ISSUE #262: [BUG]: Profile picture not cleared on logout
**Describe the bug**
After logging out, the old profile picture is still shown in the profile tab.

**To Reproduce**
1. Log in
2. Make sure profile picture is set
3. Go to settings
4. Log out
5. Profile picture is still shown (!)

**Expected behavior**
Profile picture should be cleared on logout.

**Device information:**
 - Device: Moto G9 Play
 - OS: Android 11
 - Version + build number: 1.1.0+639

### PR DESCRIPTION
**Pull request by wizlif**
The AuthBloc & ProfileBloc were being recreated (Since they are not singletons) whenever the auth screen was accessed, yet we already had them created in the app screen.

This was causing the profile screen to have a different ProfileBloc from the AuthScreen hence either the profile image wasn't updated when you signed in from a crowdaction or attempted to logout.

Closes #262 

https://user-images.githubusercontent.com/15793624/197702145-958bfc24-6558-46e1-b30b-65624c41c260.mp4

### CODE REVIEW

**Comment by Xazin** [comment]
Seems there are some errors, see the analyzer

File: lib/core/config/network_config.dart [hunk 1]
```diff
@@ -0,0 +1,32 @@
+part of '../core.dart';
+
+/// Manage all url creation and building
+// ignore_for_file: avoid_classes_with_only_static_members
+class NetworkConfig {
```
Comment (Xazin) [inline lib/core/config/network_config.dart:5]: We could have it outside a class just as functions instead of methods

**Review by Xazin — APPROVED** [review]

File: lib/core/config/network_config.dart (hunk 1 above)
Comment (Xazin) [reply lib/core/config/network_config.dart:5]: Well, it's just a function, just like any other utility functions.

You can add the SettingsRepository and get the `baseApiEndpointUrl` from it.

File: lib/core/config/network_config.dart [hunk 2]
```diff
@@ -1,32 +1,35 @@
...
 
 /// Manage all url creation and building
-// ignore_for_file: avoid_classes_with_only_static_members
-class NetworkConfig {
-  // base static url
-  static final _baseStaticUrl = dotenv.get('BASE_STATIC_ENDPOINT_URL');
+// base static url
+final _baseStaticUrl = dotenv.get('BASE_STATIC_ENDPOINT_URL');
 
+extension UserProfileUrlX on UserProfile? {
```
Comment (Xazin) [inline lib/core/config/network_config.dart:7]: What about just having this on the UserProfile instead of having them as extensions? You're using `dotenv.get` anyhow.

Comment (wizlif) [reply lib/core/config/network_config.dart:7]: Sure

Comment (wizlif) [reply lib/core/config/network_config.dart:7]: Seems it won't play nicely with nulls. Unless i still keep it as an extension

Comment (Xazin) [reply lib/core/config/network_config.dart:7]: What did you try?

**Review by Xazin — APPROVED** [review]
We might need to update pods on iOS
